package com.example.chat.entity.domain;

import java.util.Date;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.id
     *
     * @mbg.generated Mon Mar 09 14:43:26 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.uid
     *
     * @mbg.generated Mon Mar 09 14:43:26 CST 2020
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.u_name
     *
     * @mbg.generated Mon Mar 09 14:43:26 CST 2020
     */
    private String uName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.is_delete
     *
     * @mbg.generated Mon Mar 09 14:43:26 CST 2020
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.create_time
     *
     * @mbg.generated Mon Mar 09 14:43:26 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.update_time
     *
     * @mbg.generated Mon Mar 09 14:43:26 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.id
     *
     * @return the value of t_user_info.id
     *
     * @mbg.generated Mon Mar 09 14:43:26 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.id
     *
     * @param id the value for t_user_info.id
     *
     * @mbg.generated Mon Mar 09 14:43:26 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.uid
     *
     * @return the value of t_user_info.uid
     *
     * @mbg.generated Mon Mar 09 14:43:26 CST 2020
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.uid
     *
     * @param uid the value for t_user_info.uid
     *
     * @mbg.generated Mon Mar 09 14:43:26 CST 2020
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.u_name
     *
     * @return the value of t_user_info.u_name
     *
     * @mbg.generated Mon Mar 09 14:43:26 CST 2020
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.u_name
     *
     * @param uName the value for t_user_info.u_name
     *
     * @mbg.generated Mon Mar 09 14:43:26 CST 2020
     */
    public void setuName(String uName) {
        this.uName = uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.is_delete
     *
     * @return the value of t_user_info.is_delete
     *
     * @mbg.generated Mon Mar 09 14:43:26 CST 2020
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.is_delete
     *
     * @param isDelete the value for t_user_info.is_delete
     *
     * @mbg.generated Mon Mar 09 14:43:26 CST 2020
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.create_time
     *
     * @return the value of t_user_info.create_time
     *
     * @mbg.generated Mon Mar 09 14:43:26 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.create_time
     *
     * @param createTime the value for t_user_info.create_time
     *
     * @mbg.generated Mon Mar 09 14:43:26 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.update_time
     *
     * @return the value of t_user_info.update_time
     *
     * @mbg.generated Mon Mar 09 14:43:26 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.update_time
     *
     * @param updateTime the value for t_user_info.update_time
     *
     * @mbg.generated Mon Mar 09 14:43:26 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}