package com.example.connector.entity.domain;

import java.util.Date;

public class AppVersion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app_version.id
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app_version.country
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app_version.app_name
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    private String appName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app_version.version_code
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    private String versionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app_version.version_id
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    private Integer versionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app_version.client_type
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    private String clientType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app_version.update_type
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    private String updateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app_version.version_status
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    private String versionStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app_version.is_current_version
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    private Boolean isCurrentVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app_version.is_lowest_version
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    private Boolean isLowestVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app_version.create_time
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app_version.update_time
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app_version.is_delete
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app_version.operation_id
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    private Long operationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_version.id
     *
     * @return the value of t_app_version.id
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_version.id
     *
     * @param id the value for t_app_version.id
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_version.country
     *
     * @return the value of t_app_version.country
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_version.country
     *
     * @param country the value for t_app_version.country
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_version.app_name
     *
     * @return the value of t_app_version.app_name
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_version.app_name
     *
     * @param appName the value for t_app_version.app_name
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    public void setAppName(String appName) {
        this.appName = appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_version.version_code
     *
     * @return the value of t_app_version.version_code
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    public String getVersionCode() {
        return versionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_version.version_code
     *
     * @param versionCode the value for t_app_version.version_code
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    public void setVersionCode(String versionCode) {
        this.versionCode = versionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_version.version_id
     *
     * @return the value of t_app_version.version_id
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    public Integer getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_version.version_id
     *
     * @param versionId the value for t_app_version.version_id
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    public void setVersionId(Integer versionId) {
        this.versionId = versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_version.client_type
     *
     * @return the value of t_app_version.client_type
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    public String getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_version.client_type
     *
     * @param clientType the value for t_app_version.client_type
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    public void setClientType(String clientType) {
        this.clientType = clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_version.update_type
     *
     * @return the value of t_app_version.update_type
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    public String getUpdateType() {
        return updateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_version.update_type
     *
     * @param updateType the value for t_app_version.update_type
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    public void setUpdateType(String updateType) {
        this.updateType = updateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_version.version_status
     *
     * @return the value of t_app_version.version_status
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    public String getVersionStatus() {
        return versionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_version.version_status
     *
     * @param versionStatus the value for t_app_version.version_status
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    public void setVersionStatus(String versionStatus) {
        this.versionStatus = versionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_version.is_current_version
     *
     * @return the value of t_app_version.is_current_version
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    public Boolean getIsCurrentVersion() {
        return isCurrentVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_version.is_current_version
     *
     * @param isCurrentVersion the value for t_app_version.is_current_version
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    public void setIsCurrentVersion(Boolean isCurrentVersion) {
        this.isCurrentVersion = isCurrentVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_version.is_lowest_version
     *
     * @return the value of t_app_version.is_lowest_version
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    public Boolean getIsLowestVersion() {
        return isLowestVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_version.is_lowest_version
     *
     * @param isLowestVersion the value for t_app_version.is_lowest_version
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    public void setIsLowestVersion(Boolean isLowestVersion) {
        this.isLowestVersion = isLowestVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_version.create_time
     *
     * @return the value of t_app_version.create_time
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_version.create_time
     *
     * @param createTime the value for t_app_version.create_time
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_version.update_time
     *
     * @return the value of t_app_version.update_time
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_version.update_time
     *
     * @param updateTime the value for t_app_version.update_time
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_version.is_delete
     *
     * @return the value of t_app_version.is_delete
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_version.is_delete
     *
     * @param isDelete the value for t_app_version.is_delete
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_version.operation_id
     *
     * @return the value of t_app_version.operation_id
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    public Long getOperationId() {
        return operationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_version.operation_id
     *
     * @param operationId the value for t_app_version.operation_id
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    public void setOperationId(Long operationId) {
        this.operationId = operationId;
    }
}