package com.example.chat.dao.mappers;

import com.example.chat.entity.domain.MsgInfo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface MsgInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_info
     *
     * @mbg.generated Mon Mar 09 14:43:26 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_info
     *
     * @mbg.generated Mon Mar 09 14:43:26 CST 2020
     */
    int insert(MsgInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_info
     *
     * @mbg.generated Mon Mar 09 14:43:26 CST 2020
     */
    MsgInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_info
     *
     * @mbg.generated Mon Mar 09 14:43:26 CST 2020
     */
    List<MsgInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_info
     *
     * @mbg.generated Mon Mar 09 14:43:26 CST 2020
     */
    int updateByPrimaryKey(MsgInfo record);
}