package com.example.generator.dao.mappers;

import com.example.generator.entity.domain.MsgRead;
import com.example.generator.entity.domain.MsgReadExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsgReadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_read
     *
     * @mbg.generated
     */
    long countByExample(MsgReadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_read
     *
     * @mbg.generated
     */
    int deleteByExample(MsgReadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_read
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_read
     *
     * @mbg.generated
     */
    int insert(MsgRead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_read
     *
     * @mbg.generated
     */
    int insertSelective(MsgRead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_read
     *
     * @mbg.generated
     */
    List<MsgRead> selectByExample(MsgReadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_read
     *
     * @mbg.generated
     */
    MsgRead selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_read
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MsgRead record, @Param("example") MsgReadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_read
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MsgRead record, @Param("example") MsgReadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_read
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MsgRead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_read
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MsgRead record);
}