spring:
  application:
    name: connector
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://mysql:3306/chat?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      min-idle: 5
      max-active: 20

dubbo:
  application:
    name: connector
  protocol:
    name: dubbo
    port: 20880
    serialization: myprotobuf
  registry:
    address: zookeeper://ubuntu:2181
    client: curator
  scan:
    base-packages: com.example.connector.service

server:
  port: 8081

n-server:
  port: 9999

mybatis:
  mapper-locations: classpath*:com/example/connector/dao/mappers/*.xml
  type-aliases-package: com.example.connector.entity.domain

zookeeper:
  url: ubuntu:2181

redis:
  pool:
    host: ubuntu
    port: 6379
    password:
    maxTotal: 8
    maxIdle: 8
    maxWaitMillis: -1

kafka:
  nodes: ubuntu:9092
  group: push_task_group

