package com.example.connector.dao.mappers;

import com.example.connector.entity.domain.AppVersion;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface AppVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_version
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_version
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    int insert(AppVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_version
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    AppVersion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_version
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    List<AppVersion> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_version
     *
     * @mbg.generated Mon Feb 24 21:31:59 CST 2020
     */
    int updateByPrimaryKey(AppVersion record);
}