spring:
  application:
    name: push
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://mysql:3306/chat?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      min-idle: 5
      max-active: 20

dubbo:
  application:
    name: push
  protocol:
    name: dubbo
    port: 20883
    serialization: myprotobuf
  registry:
    address: zookeeper://ubuntu:2181
    client: curator
  scan:
    base-packages: com.example.push.service

server:
  port: 8083

redis:
  pool:
    host: ubuntu
    port: 6379
    password: Nijiaqi123.com
    maxTotal: 8
    maxIdle: 8
    maxWaitMillis: -1

zookeeper:
  url: ubuntu:2181

kafka:
  nodes: ubuntu:9092
  group: push_task_group




