spring:
  application:
    name: push
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/chat?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      min-idle: 5
      max-active: 20

dubbo:
  application:
    name: push
  protocol:
    name: dubbo
    port: 20883
    serialization: protostuff
  registry:
    address: zookeeper://127.0.0.1:2181
    client: curator
  scan:
    base-packages: com.example.push.service

server:
  port: 8083

redis:
  pool:
    host: 127.0.0.1
    port: 6379
    password:
    maxTotal: 8
    maxIdle: 8
    maxWaitMillis: -1

kafka:
  nodes: 127.0.0.1:9092
  group: push_task_group




