// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: outer/outer.proto

package com.example.proto.outer.outer;

public final class Outer {
  private Outer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SendMsgIndividuallyReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:outer.outer.SendMsgIndividuallyReq)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * 单聊消息请求
   * </pre>
   *
   * Protobuf type {@code outer.outer.SendMsgIndividuallyReq}
   */
  public  static final class SendMsgIndividuallyReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:outer.outer.SendMsgIndividuallyReq)
      SendMsgIndividuallyReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SendMsgIndividuallyReq.newBuilder() to construct.
    private SendMsgIndividuallyReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SendMsgIndividuallyReq() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SendMsgIndividuallyReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.proto.outer.outer.Outer.internal_static_outer_outer_SendMsgIndividuallyReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.proto.outer.outer.Outer.internal_static_outer_outer_SendMsgIndividuallyReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq.class, com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq)) {
        return super.equals(obj);
      }
      com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq other = (com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 单聊消息请求
     * </pre>
     *
     * Protobuf type {@code outer.outer.SendMsgIndividuallyReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:outer.outer.SendMsgIndividuallyReq)
        com.example.proto.outer.outer.Outer.SendMsgIndividuallyReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.proto.outer.outer.Outer.internal_static_outer_outer_SendMsgIndividuallyReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.proto.outer.outer.Outer.internal_static_outer_outer_SendMsgIndividuallyReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq.class, com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq.Builder.class);
      }

      // Construct using com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.proto.outer.outer.Outer.internal_static_outer_outer_SendMsgIndividuallyReq_descriptor;
      }

      @java.lang.Override
      public com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq getDefaultInstanceForType() {
        return com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq build() {
        com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq buildPartial() {
        com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq result = new com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq) {
          return mergeFrom((com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq other) {
        if (other == com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:outer.outer.SendMsgIndividuallyReq)
    }

    // @@protoc_insertion_point(class_scope:outer.outer.SendMsgIndividuallyReq)
    private static final com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq();
    }

    public static com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SendMsgIndividuallyReq>
        PARSER = new com.google.protobuf.AbstractParser<SendMsgIndividuallyReq>() {
      @java.lang.Override
      public SendMsgIndividuallyReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SendMsgIndividuallyReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SendMsgIndividuallyReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SendMsgIndividuallyReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.proto.outer.outer.Outer.SendMsgIndividuallyReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SendMsgIndividuallyRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:outer.outer.SendMsgIndividuallyResp)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * 单聊消息响应
   * </pre>
   *
   * Protobuf type {@code outer.outer.SendMsgIndividuallyResp}
   */
  public  static final class SendMsgIndividuallyResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:outer.outer.SendMsgIndividuallyResp)
      SendMsgIndividuallyRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SendMsgIndividuallyResp.newBuilder() to construct.
    private SendMsgIndividuallyResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SendMsgIndividuallyResp() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SendMsgIndividuallyResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.proto.outer.outer.Outer.internal_static_outer_outer_SendMsgIndividuallyResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.proto.outer.outer.Outer.internal_static_outer_outer_SendMsgIndividuallyResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp.class, com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp)) {
        return super.equals(obj);
      }
      com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp other = (com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 单聊消息响应
     * </pre>
     *
     * Protobuf type {@code outer.outer.SendMsgIndividuallyResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:outer.outer.SendMsgIndividuallyResp)
        com.example.proto.outer.outer.Outer.SendMsgIndividuallyRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.proto.outer.outer.Outer.internal_static_outer_outer_SendMsgIndividuallyResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.proto.outer.outer.Outer.internal_static_outer_outer_SendMsgIndividuallyResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp.class, com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp.Builder.class);
      }

      // Construct using com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.proto.outer.outer.Outer.internal_static_outer_outer_SendMsgIndividuallyResp_descriptor;
      }

      @java.lang.Override
      public com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp getDefaultInstanceForType() {
        return com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp build() {
        com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp buildPartial() {
        com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp result = new com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp) {
          return mergeFrom((com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp other) {
        if (other == com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:outer.outer.SendMsgIndividuallyResp)
    }

    // @@protoc_insertion_point(class_scope:outer.outer.SendMsgIndividuallyResp)
    private static final com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp();
    }

    public static com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SendMsgIndividuallyResp>
        PARSER = new com.google.protobuf.AbstractParser<SendMsgIndividuallyResp>() {
      @java.lang.Override
      public SendMsgIndividuallyResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SendMsgIndividuallyResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SendMsgIndividuallyResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SendMsgIndividuallyResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.proto.outer.outer.Outer.SendMsgIndividuallyResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DoGroupSendingReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:outer.outer.DoGroupSendingReq)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * 群发请求
   * </pre>
   *
   * Protobuf type {@code outer.outer.DoGroupSendingReq}
   */
  public  static final class DoGroupSendingReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:outer.outer.DoGroupSendingReq)
      DoGroupSendingReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DoGroupSendingReq.newBuilder() to construct.
    private DoGroupSendingReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DoGroupSendingReq() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DoGroupSendingReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.proto.outer.outer.Outer.internal_static_outer_outer_DoGroupSendingReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.proto.outer.outer.Outer.internal_static_outer_outer_DoGroupSendingReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.proto.outer.outer.Outer.DoGroupSendingReq.class, com.example.proto.outer.outer.Outer.DoGroupSendingReq.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.proto.outer.outer.Outer.DoGroupSendingReq)) {
        return super.equals(obj);
      }
      com.example.proto.outer.outer.Outer.DoGroupSendingReq other = (com.example.proto.outer.outer.Outer.DoGroupSendingReq) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.proto.outer.outer.Outer.DoGroupSendingReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.outer.outer.Outer.DoGroupSendingReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.outer.outer.Outer.DoGroupSendingReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.outer.outer.Outer.DoGroupSendingReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.outer.outer.Outer.DoGroupSendingReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.outer.outer.Outer.DoGroupSendingReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.outer.outer.Outer.DoGroupSendingReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.outer.outer.Outer.DoGroupSendingReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.outer.outer.Outer.DoGroupSendingReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.proto.outer.outer.Outer.DoGroupSendingReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.outer.outer.Outer.DoGroupSendingReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.outer.outer.Outer.DoGroupSendingReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.proto.outer.outer.Outer.DoGroupSendingReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 群发请求
     * </pre>
     *
     * Protobuf type {@code outer.outer.DoGroupSendingReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:outer.outer.DoGroupSendingReq)
        com.example.proto.outer.outer.Outer.DoGroupSendingReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.proto.outer.outer.Outer.internal_static_outer_outer_DoGroupSendingReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.proto.outer.outer.Outer.internal_static_outer_outer_DoGroupSendingReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.proto.outer.outer.Outer.DoGroupSendingReq.class, com.example.proto.outer.outer.Outer.DoGroupSendingReq.Builder.class);
      }

      // Construct using com.example.proto.outer.outer.Outer.DoGroupSendingReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.proto.outer.outer.Outer.internal_static_outer_outer_DoGroupSendingReq_descriptor;
      }

      @java.lang.Override
      public com.example.proto.outer.outer.Outer.DoGroupSendingReq getDefaultInstanceForType() {
        return com.example.proto.outer.outer.Outer.DoGroupSendingReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.proto.outer.outer.Outer.DoGroupSendingReq build() {
        com.example.proto.outer.outer.Outer.DoGroupSendingReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.proto.outer.outer.Outer.DoGroupSendingReq buildPartial() {
        com.example.proto.outer.outer.Outer.DoGroupSendingReq result = new com.example.proto.outer.outer.Outer.DoGroupSendingReq(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.proto.outer.outer.Outer.DoGroupSendingReq) {
          return mergeFrom((com.example.proto.outer.outer.Outer.DoGroupSendingReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.proto.outer.outer.Outer.DoGroupSendingReq other) {
        if (other == com.example.proto.outer.outer.Outer.DoGroupSendingReq.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.proto.outer.outer.Outer.DoGroupSendingReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.proto.outer.outer.Outer.DoGroupSendingReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:outer.outer.DoGroupSendingReq)
    }

    // @@protoc_insertion_point(class_scope:outer.outer.DoGroupSendingReq)
    private static final com.example.proto.outer.outer.Outer.DoGroupSendingReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.proto.outer.outer.Outer.DoGroupSendingReq();
    }

    public static com.example.proto.outer.outer.Outer.DoGroupSendingReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DoGroupSendingReq>
        PARSER = new com.google.protobuf.AbstractParser<DoGroupSendingReq>() {
      @java.lang.Override
      public DoGroupSendingReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DoGroupSendingReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DoGroupSendingReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DoGroupSendingReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.proto.outer.outer.Outer.DoGroupSendingReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DoGroupSendingRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:outer.outer.DoGroupSendingResp)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * 群发响应
   * </pre>
   *
   * Protobuf type {@code outer.outer.DoGroupSendingResp}
   */
  public  static final class DoGroupSendingResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:outer.outer.DoGroupSendingResp)
      DoGroupSendingRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DoGroupSendingResp.newBuilder() to construct.
    private DoGroupSendingResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DoGroupSendingResp() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DoGroupSendingResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.proto.outer.outer.Outer.internal_static_outer_outer_DoGroupSendingResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.proto.outer.outer.Outer.internal_static_outer_outer_DoGroupSendingResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.proto.outer.outer.Outer.DoGroupSendingResp.class, com.example.proto.outer.outer.Outer.DoGroupSendingResp.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.proto.outer.outer.Outer.DoGroupSendingResp)) {
        return super.equals(obj);
      }
      com.example.proto.outer.outer.Outer.DoGroupSendingResp other = (com.example.proto.outer.outer.Outer.DoGroupSendingResp) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.proto.outer.outer.Outer.DoGroupSendingResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.outer.outer.Outer.DoGroupSendingResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.outer.outer.Outer.DoGroupSendingResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.outer.outer.Outer.DoGroupSendingResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.outer.outer.Outer.DoGroupSendingResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.outer.outer.Outer.DoGroupSendingResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.outer.outer.Outer.DoGroupSendingResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.outer.outer.Outer.DoGroupSendingResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.outer.outer.Outer.DoGroupSendingResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.proto.outer.outer.Outer.DoGroupSendingResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.outer.outer.Outer.DoGroupSendingResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.outer.outer.Outer.DoGroupSendingResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.proto.outer.outer.Outer.DoGroupSendingResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 群发响应
     * </pre>
     *
     * Protobuf type {@code outer.outer.DoGroupSendingResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:outer.outer.DoGroupSendingResp)
        com.example.proto.outer.outer.Outer.DoGroupSendingRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.proto.outer.outer.Outer.internal_static_outer_outer_DoGroupSendingResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.proto.outer.outer.Outer.internal_static_outer_outer_DoGroupSendingResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.proto.outer.outer.Outer.DoGroupSendingResp.class, com.example.proto.outer.outer.Outer.DoGroupSendingResp.Builder.class);
      }

      // Construct using com.example.proto.outer.outer.Outer.DoGroupSendingResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.proto.outer.outer.Outer.internal_static_outer_outer_DoGroupSendingResp_descriptor;
      }

      @java.lang.Override
      public com.example.proto.outer.outer.Outer.DoGroupSendingResp getDefaultInstanceForType() {
        return com.example.proto.outer.outer.Outer.DoGroupSendingResp.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.proto.outer.outer.Outer.DoGroupSendingResp build() {
        com.example.proto.outer.outer.Outer.DoGroupSendingResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.proto.outer.outer.Outer.DoGroupSendingResp buildPartial() {
        com.example.proto.outer.outer.Outer.DoGroupSendingResp result = new com.example.proto.outer.outer.Outer.DoGroupSendingResp(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.proto.outer.outer.Outer.DoGroupSendingResp) {
          return mergeFrom((com.example.proto.outer.outer.Outer.DoGroupSendingResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.proto.outer.outer.Outer.DoGroupSendingResp other) {
        if (other == com.example.proto.outer.outer.Outer.DoGroupSendingResp.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.proto.outer.outer.Outer.DoGroupSendingResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.proto.outer.outer.Outer.DoGroupSendingResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:outer.outer.DoGroupSendingResp)
    }

    // @@protoc_insertion_point(class_scope:outer.outer.DoGroupSendingResp)
    private static final com.example.proto.outer.outer.Outer.DoGroupSendingResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.proto.outer.outer.Outer.DoGroupSendingResp();
    }

    public static com.example.proto.outer.outer.Outer.DoGroupSendingResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DoGroupSendingResp>
        PARSER = new com.google.protobuf.AbstractParser<DoGroupSendingResp>() {
      @java.lang.Override
      public DoGroupSendingResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DoGroupSendingResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DoGroupSendingResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DoGroupSendingResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.proto.outer.outer.Outer.DoGroupSendingResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_outer_outer_SendMsgIndividuallyReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_outer_outer_SendMsgIndividuallyReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_outer_outer_SendMsgIndividuallyResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_outer_outer_SendMsgIndividuallyResp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_outer_outer_DoGroupSendingReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_outer_outer_DoGroupSendingReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_outer_outer_DoGroupSendingResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_outer_outer_DoGroupSendingResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021outer/outer.proto\022\013outer.outer\"\030\n\026Send" +
      "MsgIndividuallyReq\"\031\n\027SendMsgIndividuall" +
      "yResp\"\023\n\021DoGroupSendingReq\"\024\n\022DoGroupSen" +
      "dingResp2\314\001\n\013ChatService\022`\n\023SendMsgIndiv" +
      "idually\022#.outer.outer.SendMsgIndividuall" +
      "yReq\032$.outer.outer.SendMsgIndividuallyRe" +
      "sp\022[\n\016DoGroupSending\022#.outer.outer.SendM" +
      "sgIndividuallyReq\032$.outer.outer.SendMsgI" +
      "ndividuallyRespB(\n\035com.example.proto.out" +
      "er.outerB\005OuterP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_outer_outer_SendMsgIndividuallyReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_outer_outer_SendMsgIndividuallyReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_outer_outer_SendMsgIndividuallyReq_descriptor,
        new java.lang.String[] { });
    internal_static_outer_outer_SendMsgIndividuallyResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_outer_outer_SendMsgIndividuallyResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_outer_outer_SendMsgIndividuallyResp_descriptor,
        new java.lang.String[] { });
    internal_static_outer_outer_DoGroupSendingReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_outer_outer_DoGroupSendingReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_outer_outer_DoGroupSendingReq_descriptor,
        new java.lang.String[] { });
    internal_static_outer_outer_DoGroupSendingResp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_outer_outer_DoGroupSendingResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_outer_outer_DoGroupSendingResp_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
